# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Michael Jolley"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Michael is a bald, bearded, builder with a passion for helping others succeed. For nearly 20 years, he’s used his experience in software development and DevOps for clients ranging from start-ups to Fortune 500.<br/><br/>When not in full-geek mode, he’s a husband, father of 3, musician and football fanatic."

# Tagline near the site title
tagline: "bald. bearded. builder."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

emptyArray: []

sass:
  sass_dir: _sass
  style: compressed

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://michaeljolley.com"

# Url for new comment submissions
comments:
  receiver: https://michaeljolley-comments.azurewebsites.net/api/PostComment

# Collections
collections:
  streams:
    output: true
    permalink: /streams/:title/

# Defaults
defaults:
  -
    scope:
      path: '_posts'
      type: posts
    values:
      comments: "true"
  -
    scope:
      path: '_streams'
      type: streams
      sort_by: date
    values:
      layout: "stream"


# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Talks
  url: /talks/
- text: Streams
  url: /streams/

# Author information - author info at the bottom of the post
author_name: "Michael Jolley"
author_bio: "Michael is a bald, bearded, builder with a passion for helping others succeed. For nearly 20 years, he’s used his experience in software development and DevOps for clients ranging from start-ups to Fortune 500."
author_url:  "https://michaeljolley.com"
author_location: "Birmingham, AL"
author_image: /images/michaeljolley.png

# Sidebar Add banner
# banner_url: "#"
# banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
# mailchimp_url: "//"

# Social links in the site footer
twitter_username: "michaeljolley"
github_username: "michaeljolley"
codepen_username: "michaeljolley"
dribbble_uername: "michaeljolley"
linkedin_username: "michaelwjolley"
twitch_username: "themichaeljolley"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: /posts/:title/
markdown: kramdown
kramdown:
    auto_ids: false
