# General Settings
name: Mike Jolley
job_title: Software Engineer
email: mikejolley@advancedsystemsunlimited.com
description: I build great products at Google, currently Google Maps. I also enjoy capturing moments with my camera and discovering new music. Follow me Twitter or drop me a line.
avatar: https://s3.amazonaws.com/uifaces/faces/twitter/dancounsell/128.jpg
favicon: /favicon.ico
twitter_handler: michaeljolley
analytics_code: UA-XXXXXXX-2
disqus: michaeljolley

# Social Accounts
social_networks:
-  { name: facebook, url: 'https://www.facebook.com/mike.jolley.940' }
-  { name: twitter, url: 'https://twitter.com/michaeljolley' }
-  { name: instagram, url: 'https://www.instagram.com/michaeljolley' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/michaelwjolley' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/MichaelJolley' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: 'http://stackoverflow.com/users/2019929/mike-jolley' }
-  { name: dribbble, url: 'https://dribbble.com/michaeljolley' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_mood: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 0
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Plugins
gems: ['jekyll-paginate']

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown

# Post Settings
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed