# General Settings
name: Mike Jolley
job_title: 
email: mikejolley@sparcapp.io
description: I build things.<br/> Husband, daddy, Christian, musician.
avatar: https://cloud.githubusercontent.com/assets/1228996/16710684/31b6f3e4-45fd-11e6-9185-ef27665fbe5b.jpg
favicon: /favicon.ico
twitter_handler: michaeljolley
comments:
  receiver: https://michaeljolley-comments.azurewebsites.net/api/PostComment
emptyArray: []

# Social Accounts
social_networks:
-  { name: twitter, url: 'https://twitter.com/michaeljolley' }
-  { name: instagram, url: 'https://www.instagram.com/michaeljolley' }
-  { name: github, url: 'https://github.com/MichaelJolley' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/michaelwjolley' }
-  { name: stack-overflow, url: 'http://stackoverflow.com/users/2019929/mike-jolley' }
-  { name: dribbble, url: 'https://dribbble.com/michaeljolley' }

# Modules Settings
show_categories: 1
show_tags: 1
show_mood: 0
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 0
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: '_posts'
      type: posts
    values:
      comments: "true"

# Serving
url: "https://michaeljolley.com"

# Includes
include: ["_pages"]

# Outputting
permalink: /archive/:year/:month/:day/:title/
category_dir: categories

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown

# Post Settings
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed