postpath: /posts/using-netlify-functions-to-add-comments-to-gridsome-sites/
message: test it out yo
name: oh its me
avatar: 'https://github.com/michaeljolley.png'
redirect: 'https://baldbeardedbuilder.com/thanks/'
identity: michaeljolley
date: 2020-06-13T02:08:13.298Z
id: 421680953
