postpath: /posts/using-netlify-functions-to-add-comments-to-gridsome/
message: >-
  Oh, I freely admit that everything I do is extra. :)  That being said, what
  would you suggest if someone didn't want to use a third-party for their static
  site comments?
name: Michael Jolley
avatar: 'https://github.com/michaeljolley.png'
redirect: 'https://baldbeardedbuilder.com/thanks/'
identity: michaeljolley
date: 2020-06-18T00:30:12.123Z
id: 1129255197
