postpath: /posts/using-netlify-functions-to-add-comments-to-gridsome/
message: Wow this is really cool
name: Umoren Samuel
avatar: >-
  https://secure.gravatar.com/avatar/1cb28b3d99388527524baa6f138b21ee?s=80&d=identicon&r=pg
redirect: 'https://baldbeardedbuilder.com/thanks/'
identity: samuelumoren365@gmail.com/Umoren
date: 2020-09-24T14:53:27.958Z
id: 1215231924
