postpath: /posts/using-netlify-functions-to-add-comments-to-gridsome/
message: here we go again
name: Michael J
avatar: 'https://github.com/michaeljolley.png'
redirect: 'https://baldbeardedbuilder.com/thanks/'
identity: michaeljolley
date: 2020-06-22T03:53:14.684Z
id: 1353247704
