postpath: /posts/using-netlify-functions-to-add-comments-to-gridsome/
message: >-
  This post is amazing. I was almost giving up on programming until I read this.
  Now I have a new passion for life and may just start building so many great
  things.
name: Robert Tables
avatar: 'https://github.com/mtheoryx.png'
redirect: 'https://baldbeardedbuilder.com/thanks/'
identity: mtheoryx
date: 2020-06-16T19:10:35.050Z
id: 1939032922
