postpath: /posts/using-netlify-functions-to-add-comments-to-gridsome/
message: >-
  Woah, thats some nice overkill for comments. :D But thanks for getting into
  the netlify functions!
name: Patrick
avatar: 'https://github.com/maybach91.png'
redirect: 'https://baldbeardedbuilder.com/thanks/'
identity: maybach91
date: 2020-06-17T19:41:23.706Z
id: 265349975
