postpath: /posts/using-netlify-functions-to-add-comments-to-gridsome/
message: testing out Akismet
name: Michael Jolley
avatar: 'https://github.com/michaeljolley.png'
redirect: 'https://baldbeardedbuilder.com/thanks/'
identity: michaeljolley
date: 2020-06-22T02:06:31.382Z
id: 601185145
